### ISSUE TITLE
[Item 35] ordinal 메서드의 사용 목적

### ISSUE THREAD

**Issue by zpqmdh** [HihoBookStudy/EffectiveJava#35]
모든 열거 타입은 해당 상수가 그 열거 타입에서 몇 번째 위치인지 반환하는 `ordinal` 이라는 메서드를 제공합니다. 
하지만, 여러 문제점 때문에 프로그래머가 이 메서드를 직접 사용할 일은 없다고 책 221페이지에서 언급하고 있습니다.

`ordinal` 메서드를 `EnumSet` 과 `EnumMap` 같이 열거 타입 기반의 범용 자료구조에 쓸 목적으로 설계되었다고 하는데, 
열거 타입 기반의 범용 자료구조에서 어떻게 `ordinal` 메서드를 사용하고 있는지 예시를 들어주실 수 있나요?

**Comment by ForteEscape** [comment]
Q.
> ordinal 메서드를 EnumSet 과 EnumMap 같이 열거 타입 기반의 범용 자료구조에 쓸 목적으로 설계되었다고 하는데,
열거 타입 기반의 범용 자료구조에서 어떻게 ordinal 메서드를 사용하고 있는지 예시를 들어주실 수 있나요?

A.
아래는 EnumSet의 구현체인 JumboEnumSet의 구현 코드 일부입니다.
```java
void addRange(E from, E to) {
    int fromIndex = from.ordinal() >>> 6;
    int toIndex = to.ordinal() >>> 6;

    if (fromIndex == toIndex) {
        elements[fromIndex] = (-1L >>>  (from.ordinal() - to.ordinal() - 1))
                        << from.ordinal();
    } else {
       elements[fromIndex] = (-1L << from.ordinal());
       for (int i = fromIndex + 1; i < toIndex; i++)
            elements[i] = -1;
        elements[toIndex] = -1L >>> (63 - to.ordinal());
    }
    size = to.ordinal() - from.ordinal() + 1;
}
```

- 보시면 Enum타입의 원소 두 개를 받아 그 사이의 모든 Enum 타입 원소를 EnumSet에 넣는 메서드입니다.
- 이때 ordinal이 힘을 발휘하는데 두 원소 사이에 있는 모든 원소를 넣기 위해서 두 원소의 위치 값이 필요합니다. 즉 `start`와 `end` 정수 값이 필요합니다.
- 이때 원소의 ordinal을 반환받음으로서 위치 정수 값들을 손쉽게 가져올 수 있습니다. 그 이후에는 for 루프로 돌면서 각 인스턴스들을 넣는 구현입니다.
- 이 뿐만 아니라 ordinal은 contains나 add, remove등의 메서드에서 인덱스의 역할을 수행하는 것을 확인할 수 있었습니다.
