### ISSUE TITLE
[Item 34] 열거 타입의 생성자

### ISSUE THREAD

**Issue by Limgayoung** [HihoBookStudy/EffectiveJava#37]
책 216쪽의 각주를 보면 열거 타입의 각 상수는 해당 열거 타입의 인스턴스를 public static final 필드로 선언했다고 되어 있습니다.

책의 예시에 나온 생성자는 상수에 대한 내용은 없이 enum의 필드에 대해서만 초기화하고 있습니다. enum에서 내부적으로 enum의 모든 상수 각각에 대해 생성자를 호출해서 각각의 객체(필드가 초기화된)를 얻는 것인지 궁금합니다. 

만일 제가 생각한 것이 아니라면 enum의 생성자가 어떻게 동작하는지 알려주실 수 있나요?

**Comment by ForteEscape** [comment]
Q.
> 책의 예시에 나온 생성자는 상수에 대한 내용은 없이 enum의 필드에 대해서만 초기화하고 있습니다. enum에서 내부적으로 enum의 모든 상수 각각에 대해 생성자를 호출해서 각각의 객체(필드가 초기화된)를 얻는 것인지 궁금합니다.

A.
- 정확합니다. Enum 내부의 각 상수들은 해당 Enum 타입의 인스턴스들입니다. 이 인스턴스들은 처음에 static 메모리에 올라가며 이후 각각 생성자를 통해 멤버 필드가 존재한다면 그 필드들을 초기화시키는 방식입니다.
