### ISSUE TITLE
[Item 39] 배열 방식과 `@Repeatable` 사용 방식의 차이 

### ISSUE THREAD

**Issue by ForteEscape** [HihoBookStudy/EffectiveJava#39]
Q.
책(p. 243)에서는 다음과 같이 설명하고 있습니다.
> 자바 8에서는 여러 개의 값을 받는 어노테이션을 다른 방식으로도 만들 수 있다. 배열 매개변수로 받는 대신 어노테이션에 `@Repeatable` 메타어노테이션을 다는 방식이다.

질문은 다음과 같습니다.
1. `@Repeatable` 어노테이션을 사용하여 구현한 방식이 배열을 사용한 방식보다 더 복잡하고, 유의할 점이 많아 보입니다. 이것이 책에서 배열을 사용하여 구현하는 방식에서 유의할 점을 생략해서 그런 것인지가 궁금합니다.
2. 만약 유의할 점이 차이가 없다면, `@Repeatable` 메타어노테이션을 사용하여 얻을 수 있는 이득이 무었인지 궁금합니다.

**Comment by zpqmdh** [comment]
배열 방식과 `@Repeatable` 어노테이션을 비교하기 위해 둘의 예시를 들어보겠습니다.

### 1. 배열 방식
```java
import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTest {
    Class<? extends Throwable>[] value();
}
```

```java
@ExceptionTest({IllegalArgumentException.class, NullPointerException.class})
public void someTest() {
    // 테스트 코드
}
```

[장점]
* 코드가 단순하고 이해하기 쉽습니다. 

[단점]
* 개별 값에 대해 추가적인 정보를 보여주기 어렵습니다. 
* 많은 값이 배열에 포함될 경우, 가독성이 떨어질 수 있습니다. 

### 2. `@Repeatable` 어노테이션
* 컨테이너 어노테이션 정의
```java
import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTests {
    ExceptionTest[] value();
}
```
* 기본 애너테이션 정의
```java
import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Repeatable(ExceptionTests.class)
public @interface ExceptionTest {
    Class<? extends Throwable> value();
}
```
```java
@ExceptionTest(IllegalArgumentException.class)
@ExceptionTest(NullPointerException.class)
public void someTest() {
    // 테스트 코드
}
```
[장점]
* 어노테이션 인스턴스를 개별적으로 다룰 수 있습니다. 따라서 각 인스턴스에 대해 추가적인 정보를 쉽게 추가할 수 있습니다.
* 여러 개의 어노테이션을 별도로 선언하여 가독성을 높일 수 있습니다. 

[단점]
* 배열 방식과 달리 컨테이너 어노테이션을 추가로 정의해야 하므로 복잡해질 수 있습니다.
* 동일한 어노테이션을 여러 번 선언해야 하기 때문에 코드가 길어질 수 있습니다. 


따라서 단순한 값의 집합을 처리할 때는 배열을 사용하는 것이 더 간편하고 직관적입니다.
하지만 각각의 애너테이션 인스턴스에 대한 유연성과 가독성이 중요할 때는 `@Repeatable`을 사용하는 것이 더 적합합니다.
