### ISSUE TITLE
[Item 48] spliterator 메서드

### ISSUE THREAD

**Issue by zpqmdh** [HihoBookStudy/EffectiveJava#40]
> p. 293 : 직접 구현한 Stream, Iterable, Collection이 병렬화의 이점을 누리려면 spliterator 메서드를 반드시 재정의하고 결과 스트림의 병렬화 성능을 강도 높게 태스트 하라.

라는 내용이 있는데 `spliterator` 메서드에 대해서 더 자세히 설명해주실 수 있나요?

**Comment by ForteEscape** [comment]
Q.
`spliterator` 메서드에 대해서 더 자세히 설명해주실 수 있나요?

A.
- spliterator 메서드는 Spliterator 타입(인터페이스 입니다.)을 반환하는 메서드입니다. 이는 기존 iterator가 반복자의 의미였다면 spliterator는 분할 가능한 반복자라는 의미를 가집니다.(그래서 분할하다의 Split과 반복자의 Iterator가 합쳐진 모양입니다.)
- 코드를 통해 확인해봅시다.

```java
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Spliterator;

public class SplitTest {

    public static void main(String[] args) {
        List<String> wordList = new ArrayList<>();

        wordList.add("apple");
        wordList.add("banana");
        wordList.add("grape");
        wordList.add("orange");
        wordList.add("mango");
        wordList.add("watermelon");

        Iterator<String> iterator = wordList.iterator();

        // 일반적인 Iterator를 통한 순차 처리
        System.out.println("기존의 iterator를 사용한 순차 출력");
        while (iterator.hasNext()) {
            System.out.println(iterator.next());
        }

        System.out.println("=====");

        // trySplit 메서드를 사용하지 않은 상태의 Spliterator 처리
        // 순차 처리와 동일하게 동작합니다.
        System.out.println("trySplit 을 사용하지 않은 Spliterator 의 출력");
        Spliterator<String> spliterator = wordList.spliterator();

        // spliterator는 forEachRemaining 메서드를 통해 내부 요소들을 순회하여 처리할 함수를 정의할 수 있습니다.
        spliterator.forEachRemaining(System.out::println);

        System.out.println("=====");

        // trySplit 메서드를 사용한 상태의 Spliterator 처리
        // 데이터를 정확히 절반으로 나누어 순차 처리합니다. 이때 순서는 고려되지 않음에 유의합니다.
        Spliterator<String> spliterator1 = wordList.spliterator();
        Spliterator<String> spliterator2 = spliterator1.trySplit();

        System.out.println("Spliterator1의 출력");
        spliterator1.forEachRemaining(System.out::println);
        System.out.println("=====");
        System.out.println("Spliterator2의 출력");
        spliterator2.forEachRemaining(System.out::println);
    }
}
```

- 결과 사진
![image](https://github.com/HihoBookStudy/EffectiveJava/assets/24915062/a7fc7a6c-10d2-466d-8a20-60d794a0501a)


- spliterator는 trySplit() 메서드를 통해 리스트 내부의 값들을 정확히 절반으로 자르려고 하며 요소의 개수가 홀수인 경우 둘 중 하나가 더 많은 수의 요소를 가지게 됩니다.
- 만약 trySplit() 메서드를 한 번도 사용하지 않을 시에는 일반적인 iterator처럼 동작하게 됩니다.
- 이렇게 구간을 통해 나누게 되면 이후 멀티스레드에서 각 구간에 대해 병렬 처리가 가능하게 되므로 멀티스레드를 사용한 프로그램에서는 이런 spliterator의 존재 여부에 따라 성능이 달라질 수 있습니다.
- 따라서 만약 저희가 커스터마이징한 Stream 또는 Iterable, Collection  타입 하위 클래스에 대해 요소를 병렬적으로 처리하기 위해서는 이런 병렬 처리를 하는데 있어 도와주는 Spliterator 인터페이스가 필요하게 됩니다.
- 이러한 이유로 저희가 커스터마이징한 Stream, Collection, Iterable 타입에 맞는 spliterator 메서드를 반드시 재정의 해야 합니다.
- 더 상세한 정보는 [해당 링크](https://devbksheen.tistory.com/entry/%EB%AA%A8%EB%8D%98-%EC%9E%90%EB%B0%94-Spliterator-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80)를 참고해 주시면 될 것 같습니다.
