### ISSUE TITLE
[Item2] Generic

### ISSUE THREAD

**Issue by IAGREEBUT** [HihoBookStudy/EffectiveJava#8]
제네릭의 여러 용법과 의미에 대해서 한번 정리해두고 가면 좋을 것 같습니다.

**Comment by Limgayoung** [comment]
5장 주제가 제네릭인데 제가 정리한 글에 대략적으로 나와있어서 전체적으로 미리 훑어보면 좋을 것 같아서 공유합니다.
https://hihinote.tistory.com/211#%EC%A0%9C%EB%84%A4%EB%A6%AD%20%ED%83%80%EC%9E%85-1
